### ISSUE TITLE
Create a story board for communicating ideas

### ISSUE THREAD

**Issue by khoiphan21** [khoiphan21/govhack2017-planning#10]
This is mainly to brainstorm for ideas + structure for the 3-minute video
- [ ] Think about a prototype idea that is achievable and help demo the concept
- [ ] Run storyboard past some GovHack crew

**Comment by weijiankong** [comment]
What to put into the videos

https://youtu.be/K-GiOtHN4FY

No longer than 3mins
Brevity and Clarity

Outline
- introduce the team
- name of the team
- team members
- photo/video clip
- name of the hack.
- Tell us about your hack. what does it do or aim to do?
- What data sets did you use
- What technology did you use, programming languages,
where to host, technical expertise, UX design, visual design, user research
- combined different datasheets
- Use a mixture of screen shots, video, audio
- plan demonstration  - show each feature in detail
- if there are missing feature, describe what is missing and what you will do next.
- demonstrate the value of your hack, who does it benefit, whose life will it make better
- include progress shots. how the hack progressed over the weekend. photo, video or screen grab of work in progress. sketches on whiteboard
- good lighting make all the difference
