### ISSUE TITLE
Prepare short statements to support the rationale for each award

### ISSUE THREAD

**Issue by khoiphan21** [khoiphan21/govhack2017-planning#23]
2020 Vision - Startups & small businesses
Best Queensland-Oriented Business Related Application
Best use of Gold Coast Data
Bounty: .tech / .space
Bounty: Plausible Futures
Bounty: The Future is Unwritten
Bringing Brisbane Together
Brisbane's Business Success
Censational Hack
Data Show Off
Innovation Hack
Innovation is Key!
Innovative presentation of economic data
Into the New hack
Marketplaces hack
Numbers hack
Places hack

**Comment by weijiankong** [comment]
I have reviewed the awards list above. I don't think we are eligible for all of the awards nominated.

I am going focus on the following in the pitch videos.

- Best Queensland-Oriented Business Related Application
- Bounty: .tech / .space
- Brisbane's Business Success
- Censational Hack
- Places hack

Please confirm
- Must use QLD data.
- Must focus on Brisbane business success and use at least 1 dataset from the Brisbane Open Data Website (http://data.brisbane.qld.gov.au)
- Data from https://data.qld.gov.au/

**Comment by weijiankong** [comment]
Completed. I couldn't attach file here but have saved under Google Drive
